# Generated by Django 2.2.19 on 2021-03-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pudelka', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Porownywarka',
        ),
    ]
