# Generated by Django 2.2.19 on 2021-03-11 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pudelka', '0002_delete_porownywarka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Porownywarka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta', models.TextField()),
                ('kalorycznosc', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ilosc_posilkow', models.SmallIntegerField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pudelka.Firma')),
            ],
        ),
    ]
