# Generated by Django 2.2.19 on 2021-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pudelka', '0003_firma_porownywarka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta', models.CharField(max_length=100)),
                ('opis', models.TextField()),
            ],
        ),
    ]
