# Generated by Django 2.2.19 on 2021-03-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pudelka', '0004_dieta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dieta',
        ),
    ]
