# Generated by Django 2.2.19 on 2021-03-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pudelka', '0005_delete_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='porownywarka',
            name='opis',
            field=models.TextField(blank=True),
        ),
    ]
