# Generated by Django 3.0.6 on 2021-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pudelka', '0006_porownywarka_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
